### PR TITLE
Create conjuncions

### PR DESCRIPTION
**Pull request by Cis112233**
Added 25 conjunctions for the program

### CODE REVIEW

**Comment by Gigabyte-Giant** [comment]
Data files need to have the `*.txt` extension, also, where is the code that implements these?

**Comment by Cis112233** [comment]
in the first PR

**Comment by Gigabyte-Giant** [comment]
Looks good, can you please [squash your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)?

**Comment by Cis112233** [comment]
I am having a bit of computer problems with git so I can't right now

**Pull request merged**
